kibana_config:
  image: docker.elastic.co/kibana/kibana:8.3.2
  volumes:
   - kibana:/usr/share/kibana
   - /etc/elastic:/etc/certs
  ports:
    - "127.0.0.1:5601:5601"

kafka_config:
  image: bitnami/kafka:3.2.0
  command:
    - /opt/bitnami/scripts/kafka/entrypoint.sh
    - "sh"
    - "-c"
    - |
      set -ex
      /opt/bitnami/scripts/kafka/setup.sh
      export KAFKA_CFG_BROKER_ID="$(kafka-storage.sh random-uuid)"
      kafka-storage.sh format --config "${KAFKA_CONF_FILE}" --cluster-id "${KAFKA_CFG_BROKER_ID}" --ignore-formatted
  env:
    ALLOW_PLAINTEXT_LISTENER: yes
    KAFKA_ENABLE_KRAFT: yes
    KAFKA_CFG_NODE_ID: 1
    KAFKA_CFG_BROKER_ID: 1
    KAFKA_BROKER_ID: 1
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
    # KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    # KAFKA_CFG_LOG_DIRS: /tmp/logs
    KAFKA_CFG_PROCESS_ROLES: broker,controller
    KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
    KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
  ports:
    - "127.0.0.1:9092:9092"

