kibana_config:
  image: docker.elastic.co/kibana/kibana:8.3.2
  volumes:
   - kibana:/usr/share/kibana
   - /etc/elastic:/etc/certs
  ports:
    - "127.0.0.1:5601:5601"

elastic_config:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
  volumes:
    - esdata01:/usr/share/elasticsearch/data
  ports:
    - "127.0.0.1:9200:9200"

podman_config:
  volumes:
    - esdata01
    - kibana
  network:
    name: 'workshopnet'