- name: Create persistent volumes for containers
  containers.podman.podman_volume:
    state: present
    name: "{{ item }}"
  loop: "{{ podman_config.volumes }}"

# - name: Create a podman network
#   containers.podman.podman_network:
#     name: "{{ podman_config.network.name }}"
#     internal: true
#     ip_range: 192.168.22.128/25
#     gateway: 192.168.22.1
#     subnet: 192.168.22.0/24
#     state: present
#     recreate: true
#   become: true
