- hosts: all
  tags: ['all', 'init']
  become: yes
  strategy: free
  roles:
    - role: generic
      tags: ['generic']

    - role: tunnel
      tags: ['tunnel']

    - role: workshop-vulns
      tags: ['workshop-vulns'] 